name: Publish php subrepo/mirror

on:
  repository_dispatch:
    types: [action-updated-time-to-test]
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update the 'a-subfolder' folder with something unique
        run: echo ${{ github.run_number }} >> a-subfolder/a-file
      - name: commit some changes to monorepo and push
        run: |
          git config --global user.name 'Monorepo user'
          git config --global user.email 'monorepo-user@noreply.github.com'
          git add a-subfolder/a-file
          git commit -m "Update monorepo file in GitHub Actions run number ${{ github.run_number }}"
          git push origin
      - uses: cucumber/action-publish-subrepo@main
        with:
          working-directory: "a-subfolder"
      - name: check that the subrepo contains our update from step 2
        run: echo "TODO"
