name: Publish subrepo

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch of the action to be tested"
        default: "main"
        required: false
        type: string
  push:

jobs:
  publish-subrepo:
    uses: cucumber/action-publish-subrepo/.github/workflows/test.yaml@${{ inputs.branch }}
    with:
      branch: ${{ inputs.branch }}
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
