name: Publish php subrepo/mirror

on:
  repository_dispatch:
    types: [action-updated-time-to-test]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update the 'php' folder with something unique
        run: echo "TODO"
      - uses: cucumber/action-publish-subrepo@main
        with:
          working-directory: "php"
      - name: check that the subrepo contains our update from step 2
        run: echo "TODO"
