name: Publish subrepo

on:
  repository_dispatch:
    types: [push]
  workflow_dispatch:
  push:

jobs:
  publish-subrepo:
    uses: cucumber/action-publish-subrepo/.github/workflows/test.yaml@main
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}